#!/usr/bin/env python3
"""Generate golden (differential) tests for hiroyannnn/jatext from the
reference implementations jaconv 0.5.0 and neologdn 0.5.6.

Usage:
    pip install -r tools/requirements.txt
    python3 tools/gen_golden.py            # writes lib/golden_*_wbtest.mbt

The output is deterministic (fixed RNG seed), so re-running it must not
produce a diff unless the reference versions or this script change.
"""
from __future__ import annotations

import os
import random
import sys
import unicodedata
from typing import Callable, Iterable

import jaconv
import neologdn

EXPECTED_JACONV = "0.5.0"
EXPECTED_NEOLOGDN = "0.5.6"
SEED = 20260928

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "lib")

if jaconv.__version__ != EXPECTED_JACONV or neologdn.__version__ != EXPECTED_NEOLOGDN:
    sys.exit(
        f"reference version mismatch: jaconv {jaconv.__version__} (want {EXPECTED_JACONV}), "
        f"neologdn {neologdn.__version__} (want {EXPECTED_NEOLOGDN})"
    )

# ---------------------------------------------------------------------------
# MoonBit literal helpers
# ---------------------------------------------------------------------------

_ESCAPE_CATEGORIES = {"Cc", "Cf", "Zs", "Zl", "Zp", "Co", "Cs", "Cn", "Mn", "Me"}


def mbt_str(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ch != " " and unicodedata.category(ch) in _ESCAPE_CATEGORIES:
            out.append("\\u{%X}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def mbt_bool(b: bool) -> str:
    return "true" if b else "false"


HEADER = (
    "// Code generated by tools/gen_golden.py. DO NOT EDIT.\n"
    f"// Reference: jaconv {EXPECTED_JACONV}, neologdn {EXPECTED_NEOLOGDN}, seed {SEED}.\n"
)


def case_block(name: str, call: str, fname: str, cases: list[tuple[str, str]]) -> str:
    """A test block that checks `call` (an expression using `input`) for each case."""
    lines = ["///|", f"test {mbt_str(name)} {{"]
    lines.append("  let cases : Array[(String, String)] = [")
    for inp, exp in cases:
        lines.append(f"    ({mbt_str(inp)}, {mbt_str(exp)}),")
    lines.append("  ]")
    lines.append("  for pair in cases {")
    lines.append("    let (input, expected) = pair")
    lines.append(f"    let actual = {call}")
    lines.append("    if actual != expected {")
    lines.append(
        f'      fail("{fname}(\\{{input}}) = \\{{actual}}, expected \\{{expected}}")'
    )
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def unchanged_block(name: str, call_on: Callable[[str], str], text: str) -> str:
    lines = ["///|", f"test {mbt_str(name)} {{"]
    lines.append(f"  let input = {mbt_str(text)}")
    lines.append(f"  assert_eq({call_on('input')}, input)")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Candidate characters
# ---------------------------------------------------------------------------


def _assigned(cps: Iterable[int]) -> list[str]:
    return [chr(c) for c in cps if unicodedata.category(chr(c)) not in ("Cn", "Cs")]


EXTRA = (
    "˗֊‐‑‒–—―⁃⁻₋−─━∼∾〜〰～﹣“”‘’¥"  # hyphen / dash / tilde / quote variants
    "漢字巴𠮷😀é"  # CJK, non-BMP, latin-1
)

CANDIDATES: list[str] = []
for ch in (
    _assigned(range(0x20, 0x7F))
    + _assigned(range(0xA0, 0x100))
    + _assigned(range(0x3000, 0x3100))
    + _assigned(range(0xFF00, 0xFFF0))
    + list(EXTRA)
):
    if ch not in CANDIDATES:
        CANDIDATES.append(ch)


def per_char(f: Callable[[str], str]) -> tuple[list[tuple[str, str]], str]:
    changed, unchanged = [], []
    for ch in CANDIDATES:
        out = f(ch)
        if out == ch:
            unchanged.append(ch)
        else:
            changed.append((ch, out))
    return changed, "".join(unchanged)


# ---------------------------------------------------------------------------
# kana: hira2kata / kata2hira / hira2hkata / enlarge_smallkana
# ---------------------------------------------------------------------------


def gen_kana() -> str:
    parts = [HEADER]
    funcs = [
        ("hira2kata", jaconv.hira2kata),
        ("kata2hira", jaconv.kata2hira),
        ("hira2hkata", jaconv.hira2hkata),
        ("enlarge_smallkana", jaconv.enlarge_smallkana),
    ]
    for name, f in funcs:
        changed, unchanged = per_char(f)
        parts.append(case_block(f"{name}: per-char mapping", f"{name}(input)", name, changed))
        parts.append(
            unchanged_block(f"{name}: untouched chars", lambda v, n=name: f"{n}({v})", unchanged)
        )

    sentences = [
        "ともえまみ",
        "まどか☆マギカ",
        "巴マミ",
        "キュゥべえ",
        "さくらきょうこ",
        "ゔぁいおりん",
        "ヴァイオリン",
        "がぎぐげご・ぱぴぷぺぽ",
        "ゝゞヽヾ",
        "𠮷野家のカレー😀",
        "",
    ]
    for name, f in funcs:
        parts.append(
            case_block(
                f"{name}: sentences", f"{name}(input)", name, [(s, f(s)) for s in sentences]
            )
        )

    # ignore= (only chars that exist in the table; jaconv raises KeyError otherwise)
    ignore_cases = [
        ("hira2kata", jaconv.hira2kata, "まどまぎ", "ど"),
        ("hira2kata", jaconv.hira2kata, "ともえまみ", "とみ"),
        ("hira2hkata", jaconv.hira2hkata, "ともえまみ", "み"),
        ("kata2hira", jaconv.kata2hira, "マミサン", "ン"),
        ("kata2hira", jaconv.kata2hira, "ティロ・フィナーレ", "ー・"),
        ("enlarge_smallkana", jaconv.enlarge_smallkana, "キュゥべえ", "ゥ"),
    ]
    for i, (name, f, text, ign) in enumerate(ignore_cases):
        exp = f(text, ignore=ign)
        parts.append(
            "\n".join(
                [
                    "///|",
                    f"test {mbt_str(f'{name}: ignore #{i}')} {{",
                    f"  assert_eq({name}({mbt_str(text)}, ignore={mbt_str(ign)}), {mbt_str(exp)})",
                    "}",
                ]
            )
            + "\n"
        )
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# width: z2h / h2z with all flag combinations
# ---------------------------------------------------------------------------

FLAG_COMBOS = [
    (k, a, d) for k in (True, False) for a in (False, True) for d in (False, True)
]


def gen_width(rng: random.Random) -> str:
    parts = [HEADER]
    for fname, f in (("z2h", jaconv.z2h), ("h2z", jaconv.h2z)):
        for kana, ascii_, digit in FLAG_COMBOS:
            label = f"kana={mbt_bool(kana)} ascii={mbt_bool(ascii_)} digit={mbt_bool(digit)}"
            call = (
                f"{fname}(input, kana={mbt_bool(kana)}, ascii={mbt_bool(ascii_)}, "
                f"digit={mbt_bool(digit)})"
            )
            g = lambda s, f=f, k=kana, a=ascii_, d=digit: f(s, kana=k, ascii=a, digit=d)
            changed, unchanged = per_char(g)
            if changed:
                parts.append(case_block(f"{fname} {label}: per-char mapping", call, fname, changed))
            parts.append(
                unchanged_block(
                    f"{fname} {label}: untouched chars",
                    lambda v, fn=fname, k=kana, a=ascii_, d=digit: (
                        f"{fn}({v}, kana={mbt_bool(k)}, ascii={mbt_bool(a)}, digit={mbt_bool(d)})"
                    ),
                    unchanged,
                )
            )

    # h2z dakuten / handakuten composition in context
    dakuten_cases = [
        "ｶﾞｷﾞｸﾞｹﾞｺﾞ",
        "ﾊﾟﾋﾟﾌﾟﾍﾟﾎﾟ",
        "ｳﾞｧｲｵﾘﾝ",
        "ﾃｨﾛﾌｨﾅｰﾚ",
        "ｶﾟ",
        "ﾞﾟ",
        "ｱﾞ",
        "ﾊﾞﾟ",
        "ﾊﾟﾞ",
        "ｶﾞｶﾞ",
        "abc ﾀﾞｲｽｷ 123",
    ]
    alphabet = list("ｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾊﾋﾌﾍﾎｳｱﾝｰﾞﾟﾞﾟaZ1 ｧ･｢｣｡､")
    for _ in range(200):
        n = rng.randint(1, 10)
        dakuten_cases.append("".join(rng.choice(alphabet) for _ in range(n)))
    for kana, ascii_, digit in [(True, False, False), (True, True, True), (False, True, True)]:
        label = f"kana={mbt_bool(kana)} ascii={mbt_bool(ascii_)} digit={mbt_bool(digit)}"
        call = (
            f"h2z(input, kana={mbt_bool(kana)}, ascii={mbt_bool(ascii_)}, digit={mbt_bool(digit)})"
        )
        cases = [(s, jaconv.h2z(s, kana=kana, ascii=ascii_, digit=digit)) for s in dakuten_cases]
        parts.append(case_block(f"h2z {label}: dakuten in context", call, "h2z", cases))

    # ignore= (quirk: the dakuten pre-pass ignores `ignore`)
    ignore_cases = [
        ("h2z", "ﾃｨﾛﾌｨﾅｰﾚ", "ｨ", True, False, False),
        ("h2z", "ｶﾞ", "ｶ", True, False, False),
        ("h2z", "abcd", "b", True, True, False),
        ("z2h", "ティロフィナーレ", "ィ", True, False, False),
        ("z2h", "ＡＢＣＤ１２３４", "Ｂ２", True, True, True),
    ]
    for i, (fname, text, ign, k, a, d) in enumerate(ignore_cases):
        f = jaconv.h2z if fname == "h2z" else jaconv.z2h
        exp = f(text, ignore=ign, kana=k, ascii=a, digit=d)
        parts.append(
            "\n".join(
                [
                    "///|",
                    f"test {mbt_str(f'{fname}: ignore #{i}')} {{",
                    f"  assert_eq({fname}({mbt_str(text)}, ignore={mbt_str(ign)}, "
                    f"kana={mbt_bool(k)}, ascii={mbt_bool(a)}, digit={mbt_bool(d)}), {mbt_str(exp)})",
                    "}",
                ]
            )
            + "\n"
        )
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# normalize (neologdn)
# ---------------------------------------------------------------------------

TILDES = [
    ("remove", "Tilde::Remove"),
    ("ignore", "Tilde::Ignore"),
    ("normalize", "Tilde::Normalize"),
    ("normalize_zenkaku", "Tilde::NormalizeZenkaku"),
]

NORMALIZE_CURATED = [
    # neologdn test suite
    "０",
    "ﾊﾝｶｸ",
    "o₋o",
    "majika━",
    "わ〰い",
    "スーパーーーー",
    "!#",
    "ゼンカク　スペース",
    "お             お",
    "      おお",
    "おお      ",
    "検索 エンジン 自作 入門 を 買い ました!!!",
    "アルゴリズム C",
    "　　　ＰＲＭＬ　　副　読　本　　　",
    "Coding the Matrix",
    "南アルプスの　天然水　Ｓｐａｒｋｉｎｇ　Ｌｅｍｏｎ　レモン一絞り",
    "南アルプスの　天然水-　Ｓｐａｒｋｉｎｇ*　Ｌｅｍｏｎ+　レモン一絞り",
    "ﾊﾟﾊﾟ",
    "a˗֊‐‑‒–⁃⁻₋−",
    "あ﹣－ｰ—―─━ー",
    "チルダ~∼∾〜〰～",
    "う゛ほﾟ",
    "A ˗あ",
    "A ーあ",
    "A ～あ",
    # documented quirks
    "１－２",
    "か゛",
    "は゜",
    "¥100",
    "＼",
    "“x” ‘y’",
    "😀 a",
    "é b",
    "a * b",
    "a　あ",
    "ｰ-",
    "",
    " ",
    "　",
    "a",
    "a ",
    " a",
    "a b",
    "a  b",
    "あ い",
    "a あ",
    "あ a",
    "1467〜1487年",
    "1467~1487年",
    "巴 マミ",
    "ﾃｨﾛ･ﾌｨﾅｰﾚ",
    "（株）ＡＢＣ　ホールディングス",
    "TEL：０３－１２３４－５６７８",
    "ｳﾞｧｲｵﾘﾝ",
    "𠮷野家 の カレー",
    "line1\nline2",
    "tab\tsep",
]

FUZZ_ALPHABET = list(
    "aZ1０Ａｘｶﾞﾟﾊｳう゛゜はかｰーー━－-˗~〜～*あ漢ア。!(（)¥”“’‘é\n"
) + [" ", " ", " ", "　", "　", "😀", "𠮷"]


def gen_normalize(rng: random.Random) -> str:
    parts = [HEADER]
    N = neologdn.normalize

    # per-char, default options
    cases = [(ch, N(ch)) for ch in CANDIDATES]
    parts.append(case_block("normalize: per-char (defaults)", "normalize(input)", "normalize", cases))

    # curated, all tilde modes x remove_space
    for tilde, tilde_mbt in TILDES:
        for remove_space in (True, False):
            label = f"tilde={tilde} remove_space={mbt_bool(remove_space)}"
            call = f"normalize(input, remove_space={mbt_bool(remove_space)}, tilde={tilde_mbt})"
            cs = [(s, N(s, remove_space=remove_space, tilde=tilde)) for s in NORMALIZE_CURATED]
            parts.append(case_block(f"normalize {label}: curated", call, "normalize", cs))

    # repeat option
    repeat_inputs = [
        "うまああああああああああああい",
        "かわいいいいいるい",
        "オラオラオラオラーッ",
        "無駄無駄無駄無駄ァ",
        "ｗｗｗｗｗｗ",
        "！！！！？？？",
        "ﾊﾊﾊﾊﾊﾊ",
        "隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、言えた！",
    ]
    for repeat in (1, 2, 3):
        for max_len in (8, 0, 2):
            call = f"normalize(input, repeat={repeat}, max_repeat_substr_length={max_len})"
            cs = [(s, N(s, repeat=repeat, max_repeat_substr_length=max_len)) for s in repeat_inputs]
            parts.append(
                case_block(
                    f"normalize repeat={repeat} max_repeat_substr_length={max_len}",
                    call,
                    "normalize",
                    cs,
                )
            )

    # seeded fuzz: defaults
    fuzz = []
    for _ in range(600):
        n = rng.randint(0, 14)
        s = "".join(rng.choice(FUZZ_ALPHABET) for _ in range(n))
        fuzz.append((s, N(s)))
    parts.append(case_block("normalize: fuzz (defaults)", "normalize(input)", "normalize", fuzz))

    # seeded fuzz: other option combos
    for tilde, tilde_mbt in TILDES:
        for remove_space in (True, False):
            if tilde == "remove" and remove_space:
                continue
            fz = []
            for _ in range(80):
                n = rng.randint(0, 14)
                s = "".join(rng.choice(FUZZ_ALPHABET) for _ in range(n))
                fz.append((s, N(s, remove_space=remove_space, tilde=tilde)))
            call = f"normalize(input, remove_space={mbt_bool(remove_space)}, tilde={tilde_mbt})"
            parts.append(
                case_block(
                    f"normalize tilde={tilde} remove_space={mbt_bool(remove_space)}: fuzz",
                    call,
                    "normalize",
                    fz,
                )
            )
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# shorten_repeat (neologdn)
# ---------------------------------------------------------------------------


def gen_repeat(rng: random.Random) -> str:
    parts = [HEADER]
    S = neologdn.shorten_repeat
    fixed = [
        ("うまああああああああああああい", 7, 0),
        ("かわいいいいいるい", 6, 0),
        ("オラオラオラオラーッ", 2, 0),
        ("無駄無駄無駄無駄ァ", 1, 0),
        ("隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、言えた！", 1, 0),
        ("隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、隣の客はよく柿食う客だ、言えた！", 1, 11),
        ("ああああ", 2, 8),
        ("ababab", 1, 8),
        ("😀😀😀😀", 1, 8),
        ("𠮷𠮷𠮷a", 2, 8),
        ("", 1, 8),
    ]
    for threshold, max_len in [(1, 8), (2, 8), (3, 8), (1, 0), (2, 2), (1, 1)]:
        cs = [(t, S(t, r, m)) for (t, r, m) in fixed if r == threshold and m == max_len]
        alphabet = list("abあい😀")
        for _ in range(60):
            n = rng.randint(0, 14)
            s = "".join(rng.choice(alphabet) for _ in range(n))
            cs.append((s, S(s, threshold, max_len)))
        call = f"shorten_repeat(input, {threshold}, max_repeat_substr_length={max_len})"
        parts.append(
            case_block(
                f"shorten_repeat threshold={threshold} max_repeat_substr_length={max_len}",
                call,
                "shorten_repeat",
                cs,
            )
        )
    # fixed cases whose params were not covered above
    covered = {(1, 8), (2, 8), (3, 8), (1, 0), (2, 2), (1, 1)}
    rest = [(t, r, m) for (t, r, m) in fixed if (r, m) not in covered]
    for i, (t, r, m) in enumerate(rest):
        parts.append(
            "\n".join(
                [
                    "///|",
                    f"test {mbt_str(f'shorten_repeat: fixed #{i}')} {{",
                    f"  assert_eq(shorten_repeat({mbt_str(t)}, {r}, max_repeat_substr_length={m}), "
                    f"{mbt_str(S(t, r, m))})",
                    "}",
                ]
            )
            + "\n"
        )
    return "\n".join(parts)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    rng = random.Random(SEED)
    files = {
        "golden_kana_wbtest.mbt": gen_kana(),
        "golden_width_wbtest.mbt": gen_width(rng),
        "golden_normalize_wbtest.mbt": gen_normalize(rng),
        "golden_repeat_wbtest.mbt": gen_repeat(rng),
    }
    for name, content in files.items():
        path = os.path.join(OUT_DIR, name)
        with open(path, "w", encoding="utf-8", newline="\n") as fp:
            fp.write(content)
        print(f"wrote {os.path.relpath(path)} ({content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
